"use client";
import { useEffect, useState } from "react";
import { API_URL as API } from "@/utils/api";
const token = () => typeof window !== "undefined" ? localStorage.getItem("nexusai_token") : "";

const STATUS_COLORS: Record<string, string> = {
  draft: "#6366F1",
  sent: "#F59E0B",
  accepted: "#4FFFB0",
  rejected: "#EF4444",
};

function StatusBadge({ status }: { status: string }) {
  const color = STATUS_COLORS[status] || "#888";
  return (
    <span style={{
      background: color + "22", color, padding: "3px 10px",
      borderRadius: 5, fontSize: 11, fontFamily: "monospace", textTransform: "uppercase",
    }}>
      {status}
    </span>
  );
}

export default function Quotes() {
  const [quotes, setQuotes] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const fetchQuotes = () => {
    setLoading(true);
    fetch(`${API}/api/quotes/`, { headers: { Authorization: `Bearer ${token()}` } })
      .then(r => r.json())
      .then(data => { setQuotes(Array.isArray(data) ? data : []); setLoading(false); })
      .catch(() => setLoading(false));
  };

  useEffect(() => { fetchQuotes(); }, []);

  const updateStatus = async (id: string, status: string) => {
    await fetch(`${API}/api/quotes/${id}/status`, {
      method: "PATCH",
      headers: { Authorization: `Bearer ${token()}`, "Content-Type": "application/json" },
      body: JSON.stringify({ status }),
    });
    fetchQuotes();
    if (selected?.id === id) setSelected((q: any) => ({ ...q, status }));
  };

  return (
    <div style={{ display: "flex", gap: 20, height: "100%" }}>
      {/* Quote list */}
      <div style={{ flex: 1 }}>
        <h2 style={{ fontSize: 22, fontWeight: 800, marginBottom: 6 }}>Quotes</h2>
        <p style={{ color: "rgba(255,255,255,0.4)", fontSize: 14, marginBottom: 20 }}>
          Instant price estimates generated by the AI agent.
        </p>

        {loading && <div style={{ color: "rgba(255,255,255,0.3)", textAlign: "center", padding: 40 }}>Loading…</div>}

        {!loading && quotes.length === 0 && (
          <div style={{ color: "rgba(255,255,255,0.3)", textAlign: "center", padding: 40, fontFamily: "monospace", fontSize: 13 }}>
            No quotes yet. The agent generates quotes automatically when customers ask for estimates.
          </div>
        )}

        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          {quotes.map(q => (
            <div
              key={q.id}
              onClick={() => setSelected(q)}
              style={{
                background: selected?.id === q.id ? "rgba(79,255,176,0.06)" : "rgba(255,255,255,0.03)",
                border: `1px solid ${selected?.id === q.id ? "rgba(79,255,176,0.3)" : "rgba(255,255,255,0.08)"}`,
                borderRadius: 10, padding: "12px 16px", cursor: "pointer",
                display: "flex", alignItems: "center", gap: 14,
              }}
            >
              <div style={{ flex: 1 }}>
                <div style={{ color: "#e8eaf0", fontWeight: 600, fontSize: 14 }}>
                  {q.contact_name || "Anonymous"} — {q.currency} {q.subtotal?.toFixed(2)}
                </div>
                <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 12, marginTop: 2 }}>
                  {q.chat_summary || `${(q.line_items || []).length} line items`}
                </div>
              </div>
              <StatusBadge status={q.status} />
              <span style={{ color: "rgba(255,255,255,0.3)", fontSize: 12 }}>
                {q.created_at ? new Date(q.created_at).toLocaleDateString() : ""}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Quote detail */}
      {selected && (
        <div style={{
          width: 360, background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)",
          borderRadius: 12, padding: 24, flexShrink: 0,
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
            <h3 style={{ fontSize: 16, fontWeight: 700, margin: 0 }}>Quote Detail</h3>
            <button onClick={() => setSelected(null)}
              style={{ background: "none", border: "none", color: "rgba(255,255,255,0.4)", cursor: "pointer", fontSize: 18 }}>×</button>
          </div>

          <div style={{ marginBottom: 12 }}>
            <StatusBadge status={selected.status} />
          </div>

          <div style={{ marginBottom: 12 }}>
            <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 11, marginBottom: 4 }}>CUSTOMER</div>
            <div style={{ color: "#e8eaf0", fontSize: 14 }}>{selected.contact_name || "—"}</div>
            <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 12 }}>{selected.contact_email || ""}</div>
          </div>

          <div style={{ marginBottom: 12 }}>
            <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 11, marginBottom: 4 }}>LINE ITEMS</div>
            {(selected.line_items || []).map((item: any, i: number) => (
              <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "6px 0",
                borderBottom: "1px solid rgba(255,255,255,0.05)", fontSize: 13 }}>
                <span style={{ color: "rgba(255,255,255,0.7)" }}>{item.description}</span>
                <span style={{ color: "#4FFFB0", fontFamily: "monospace" }}>{selected.currency} {Number(item.price).toFixed(2)}</span>
              </div>
            ))}
            <div style={{ display: "flex", justifyContent: "space-between", paddingTop: 8, fontWeight: 700 }}>
              <span style={{ color: "#e8eaf0" }}>Total</span>
              <span style={{ color: "#4FFFB0", fontFamily: "monospace" }}>{selected.currency} {selected.subtotal?.toFixed(2)}</span>
            </div>
          </div>

          {selected.notes && (
            <div style={{ marginBottom: 16 }}>
              <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 11, marginBottom: 4 }}>NOTES</div>
              <div style={{ color: "rgba(255,255,255,0.6)", fontSize: 13 }}>{selected.notes}</div>
            </div>
          )}

          {selected.valid_until && (
            <div style={{ marginBottom: 16 }}>
              <div style={{ color: "rgba(255,255,255,0.4)", fontSize: 11, marginBottom: 4 }}>VALID UNTIL</div>
              <div style={{ color: "rgba(255,255,255,0.6)", fontSize: 13 }}>{new Date(selected.valid_until).toLocaleDateString()}</div>
            </div>
          )}

          {/* Status actions */}
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 8 }}>
            {["sent", "accepted", "rejected"].filter(s => s !== selected.status).map(s => (
              <button key={s} onClick={() => updateStatus(selected.id, s)}
                style={{
                  background: (STATUS_COLORS[s] || "#888") + "22",
                  border: `1px solid ${STATUS_COLORS[s] || "#888"}44`,
                  color: STATUS_COLORS[s] || "#888",
                  padding: "6px 14px", borderRadius: 6, cursor: "pointer", fontSize: 12, textTransform: "capitalize",
                }}>
                Mark {s}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
