"""
Quotes API
──────────
CRUD endpoints for instant price estimates generated by the agent.
"""
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import Optional
import uuid

from app.core.database import get_db
from app.core.auth import get_current_user, get_current_tenant
from app.models.quote import Quote
from app.services.quote_generator import generate_quote

router = APIRouter()


class GenerateQuoteRequest(BaseModel):
    requirements: str
    currency: str = "GBP"


@router.get("/")
async def list_quotes(
    tenant=Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Quote)
        .where(Quote.tenant_id == tenant.id)
        .order_by(Quote.created_at.desc())
        .limit(100)
    )
    quotes = result.scalars().all()
    return [_serialize(q) for q in quotes]


@router.get("/{quote_id}")
async def get_quote(
    quote_id: str,
    tenant=Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Quote).where(Quote.id == quote_id, Quote.tenant_id == tenant.id)
    )
    quote = result.scalar_one_or_none()
    if not quote:
        raise HTTPException(status_code=404, detail="Quote not found")
    return _serialize(quote)


@router.post("/generate")
async def create_quote(
    body: GenerateQuoteRequest,
    tenant=Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    result = await generate_quote(
        requirements=body.requirements,
        tenant_id=str(tenant.id),
        db=db,
        currency=body.currency,
    )
    if "error" in result:
        raise HTTPException(status_code=500, detail=result["error"])
    return result


@router.patch("/{quote_id}/status")
async def update_quote_status(
    quote_id: str,
    body: dict,
    tenant=Depends(get_current_tenant),
    db: AsyncSession = Depends(get_db),
):
    allowed = {"draft", "sent", "accepted", "rejected"}
    new_status = body.get("status")
    if new_status not in allowed:
        raise HTTPException(status_code=400, detail=f"Status must be one of {allowed}")

    result = await db.execute(
        select(Quote).where(Quote.id == quote_id, Quote.tenant_id == tenant.id)
    )
    quote = result.scalar_one_or_none()
    if not quote:
        raise HTTPException(status_code=404, detail="Quote not found")

    quote.status = new_status
    from datetime import datetime
    if new_status == "sent":
        quote.sent_at = datetime.utcnow()
    elif new_status == "accepted":
        quote.accepted_at = datetime.utcnow()

    await db.commit()
    return _serialize(quote)


def _serialize(q: Quote) -> dict:
    return {
        "id": str(q.id),
        "tenant_id": str(q.tenant_id),
        "lead_id": str(q.lead_id) if q.lead_id else None,
        "customer_id": str(q.customer_id) if q.customer_id else None,
        "line_items": q.line_items or [],
        "subtotal": q.subtotal,
        "currency": q.currency,
        "notes": q.notes,
        "chat_summary": q.chat_summary,
        "status": q.status,
        "valid_until": q.valid_until.isoformat() if q.valid_until else None,
        "contact_name": q.contact_name,
        "contact_email": q.contact_email,
        "created_at": q.created_at.isoformat() if q.created_at else None,
    }
